#!/bin/bash

prg=./try

for t in Test/Test_* ; do
    echo ${t##*/}
    $prg <$t/inp 2>&1 >$t/out
    diff -q -w $t/exp $t/out 2>&1 >/dev/null || echo ${t##*/} failed >&2
done

# Manually tested history, basic foreground and background commands by using the 'ps' command
#   to check if a process like 'sleep 10' was running the background while I could type in another
#   command. Unable to get to through testing aside from manual command line work. 
